### ISSUE TITLE
Can this code run on GPUs such as 3090 or A100?

### ISSUE THREAD

**Issue by wutaiqiang** [for-ai/parameter-efficient-moe#3]
This code seems to be used on TPUs.

Can I run the code on 3090 or A100? If so, what should I change?

Thanks~

**Comment by ahmetustun** [comment]
Hi, 

Thanks for the question. We used this code only on TPUs, and did not test on GPUs. It should be usable with GPUs but may require some changes. Please check the T5x instructions here:

https://github.com/google-research/t5x/blob/main/README.md#gpu-usage

**Comment by wutaiqiang** [comment]
thanks～
